#!/usr/bin/python3
import os
import py_compile
import sys

# Get the Python script filename from the environment variable
pyfile = os.getenv('PYFILE')

if pyfile:
    # Compile the Python script
    try:
        py_compile.compile(pyfile, cfile=pyfile + 'c')
        sys.exit(0)
    except Exception as e:
        sys.stderr.write(f"Error compiling {pyfile}: {e}\n")
        sys.exit(1)
else:
    sys.stderr.write("Environment variable PYFILE not set.\n")
    sys.exit(1)

